version: '2'
services:
  database:
    build:
      context: ../
      dockerfile: docker/database.dockerfile
    image: percona:latest
    container_name: mysql_xiagag
    volumes:
      - dbdata_xiagag3:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33063:3306"
  app:
    build:
      context: ../
      dockerfile: docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ../:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8282:80


volumes:
  dbdata_xiagag3: